### ISSUE TITLE
"Cannot load such file" error when running

### ISSUE THREAD

**Issue by Bauke** [clonex10100/tildes-scraper#2]
Hi, when running I'm getting an error that it can't load a file. Any ideas on what this might be? I'm not familiar with Ruby at all so I don't know if this is a tilde-scraper problem or a me problem. :P

```
$ tilde-scraper
Traceback (most recent call last):
        10: from /home/bauke/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
         9: from /home/bauke/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
         8: from /home/bauke/.rvm/gems/ruby-2.6.5/bin/tilde-scraper:23:in `<main>'
         7: from /home/bauke/.rvm/gems/ruby-2.6.5/bin/tilde-scraper:23:in `load'
         6: from /home/bauke/.rvm/gems/ruby-2.6.5/gems/tilde-scraper-0.0.2/bin/tilde-scraper:2:in `<top (required)>'
         5: from /home/bauke/.rvm/gems/ruby-2.6.5/gems/tilde-scraper-0.0.2/bin/tilde-scraper:2:in `require_relative'
         4: from /home/bauke/.rvm/gems/ruby-2.6.5/gems/tilde-scraper-0.0.2/lib/tilde_scraper.rb:3:in `<top (required)>'
         3: from /home/bauke/.rvm/gems/ruby-2.6.5/gems/tilde-scraper-0.0.2/lib/tilde_scraper.rb:3:in `require_relative'
         2: from /home/bauke/.rvm/gems/ruby-2.6.5/gems/tilde-scraper-0.0.2/config/enviornment.rb:2:in `<top (required)>'         1: from /home/bauke/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/bauke/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pry (LoadError)
```

**Comment by clonex10100** [comment]
It looks like I messed up my gem dependencies, it should work now. Thanks for letting me know.
